# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f173b5ef3b37d8f12234fe02fee66115567dc4bda3c8e89dd06044f1fda60211d29e7412ea772a9b420513f37a8492b915153d28b08c16e24868aa03b9896087

test:
  secret_key_base: ef8ed282ad770f7b51db1f9df7ff5eb19d1ed3ab2f44963130efc9ce4112ddd2b2b7fd0963700a7588393a4cd5645add1b2f630ee50a9d27e0f135ca5975ed8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
